apiVersion: v1
kind: Service
metadata:
  name: newsfeed-service
  labels:
    app: newsfeed
spec:
  type: NodePort
  selector:
    app: newsfeed
  ports:
  - port: 80
    targetPort: 30007
    nodePort: 30007
    protocol: TCP
